version: "3.8"

services:
  bot:
    build: .
    container_name: safe_bot
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - safe_network
    env_file:
      - .env
    command: >
      sh -c "while ! pg_isready -h db -p 5432; do echo 'Waiting for db...'; sleep 2; done;
      python bot/bot.py"

  db:
    image: postgres:13
    container_name: safe_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - safe_network

volumes:
  postgres_data:

networks:
  safe_network:
    driver: bridge
