"""Initial revision

Revision ID: 2dafdf78e52f
Revises: 
Create Date: 2025-05-17 14:20:59.473419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dafdf78e52f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'logs', 'users', ['user_id'], ['tg_id'])
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['tg_id'])
    op.create_foreign_key(None, 'security_step_progresss', 'users', ['user_id'], ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'security_step_progresss', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'logs', type_='foreignkey')
    # ### end Alembic commands ###
